server:
 servlet:
   context-path: /EmployeePortalWithSecurityJDBC
spring:
 datasource: 
   url: jdbc:mysql://localhost/employeeportal
   username: root
   password: rootpassword
   driver-class-name : com.mysql.jdbc.Driver
   type: org.apache.tomcat.jdbc.pool.DataSource
 
 mail:
    host: smtp.gmail.com
    port: 587
    username: rj222189@gmail.com
    password: pass@123
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
        
hibernate:
 dialect: org.hibernate.dialect.MySQLInnoDBDialect
 show_sql: true
 hbm2ddl:
   auto: validate
 c3p0:
   min_size: 5
   max_size: 20
   acquire_increment: 1
   timeout: 1800
   max_statements: 150